# Generated by Django 4.2 on 2026-03-28 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0003_tenant_domain_tenant_location_tenant_timezone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("media", "0012_detection_unique_detection_per_image_checksum"),
        ("api_keys", "0002_apikey_owned_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "label_pattern",
                    models.CharField(
                        help_text='Regex or exact match pattern for detection labels (e.g. "rust", "crack|corrosion")',
                        max_length=200,
                    ),
                ),
                (
                    "min_confidence",
                    models.FloatField(
                        default=0.5,
                        help_text="Minimum detection confidence to trigger alert (0.0-1.0)",
                    ),
                ),
                (
                    "plant_site",
                    models.CharField(
                        blank=True,
                        help_text="If set, only trigger for this plant site. Null means any plant.",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "webhook_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional webhook URL for Slack/Teams/PagerDuty notifications",
                        null=True,
                    ),
                ),
                (
                    "notify_websocket",
                    models.BooleanField(
                        default=True,
                        help_text="Push alert via WebSocket to connected clients",
                    ),
                ),
                (
                    "cooldown_minutes",
                    models.IntegerField(
                        default=5,
                        help_text="Suppress repeat alerts for same label+plant within this window",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alert_rules_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by_api_key",
                    models.ForeignKey(
                        blank=True,
                        help_text="API key used to create this record, if applicable.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to="api_keys.apikey",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                        ],
                        default="warning",
                        max_length=10,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("confidence", models.FloatField()),
                ("plant_site", models.CharField(blank=True, max_length=200, null=True)),
                ("is_acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("webhook_sent", models.BooleanField(default=False)),
                ("webhook_response", models.TextField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "alert_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="alerts.alertrule",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by_api_key",
                    models.ForeignKey(
                        blank=True,
                        help_text="API key used to create this record, if applicable.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to="api_keys.apikey",
                    ),
                ),
                (
                    "detection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="media.detection",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="media.image",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["tenant", "is_active"], name="alerts_aler_tenant__b60953_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="alertrule",
            unique_together={("tenant", "name")},
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["tenant", "is_acknowledged"],
                name="alerts_aler_tenant__eb9d64_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["tenant", "severity"], name="alerts_aler_tenant__b4606e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["tenant", "created_at"], name="alerts_aler_tenant__c71dff_idx"
            ),
        ),
    ]
