[inet_http_server]
port=%(ENV_SUPERVISOR_HOST)s:%(ENV_SUPERVISOR_PORT)s
chmod=0777
chown=nobody:nogroup
username=%(ENV_SUPERVISOR_USERNAME)s
password=%(ENV_SUPERVISOR_PASSWORD)s

[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
user=root

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
  
[supervisorctl]
serverurl=http://%(ENV_SUPERVISOR_HOST)s:%(ENV_SUPERVISOR_PORT)s
username=%(ENV_SUPERVISOR_USERNAME)s
password=%(ENV_SUPERVISOR_PASSWORD)s

[program:core]
environment=PYTHONPATH=/home/%(ENV_user)s/src/backend
command=gunicorn -w 2 backend.wsgi -b %(ENV_DJANGO_ADMIN_HOST)s:%(ENV_DJANGO_ADMIN_PORT)s --reload
directory=/home/%(ENV_user)s/src/backend
autostart=true
autorestart=true
stderr_logfile=/var/log/core.err.log
stdout_logfile=/var/log/core.out.log

[program:api]
environment=PYTHONPATH=/home/%(ENV_user)s/src/backend
command=gunicorn -w 4 -k uvicorn.workers.UvicornWorker api.main:app -b %(ENV_SEARCH_ENGINE_HOST)s:%(ENV_SEARCH_ENGINE_PORT)s --reload
directory=/home/%(ENV_user)s/src/backend
autostart=true
autorestart=true
stderr_logfile=/var/log/api.err.log
stdout_logfile=/var/log/api.out.log