# Generated by Django 4.2 on 2026-02-20 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0003_tenant_domain_tenant_location_tenant_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_type', models.CharField(choices=[('image', 'Image'), ('text', 'Text'), ('video', 'Video'), ('hybrid', 'Hybrid')], max_length=20)),
                ('query_text', models.TextField(blank=True, null=True)),
                ('query_image_path', models.CharField(blank=True, max_length=512, null=True)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('results_count', models.IntegerField()),
                ('top_result_id', models.UUIDField(blank=True, null=True)),
                ('execution_time_ms', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'search_queries',
                'default_manager_name': 'objects',
            },
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['tenant', 'created_at'], name='search_quer_tenant__df9359_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['tenant', 'query_type'], name='search_quer_tenant__8daf2b_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['user'], name='search_quer_user_id_64dda1_idx'),
        ),
    ]
