# Generated by Django 4.2 on 2026-03-17 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0002_apikey_owned_by'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='created_by_api_key',
            field=models.ForeignKey(blank=True, help_text='API key used to create this record, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='api_keys.apikey'),
        ),
    ]
