# Generated by Django 4.2 on 2026-02-27 14:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_domain_tenant_location_tenant_timezone'),
        ('embeddings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantVectorCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_vector_collection_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('collection_name', models.CharField(help_text='Unique collection name in vector DB', max_length=255, unique=True)),
                ('db_type', models.CharField(choices=[('qdrant', 'Qdrant'), ('faiss', 'FAISS')], help_text='Vector database type', max_length=50)),
                ('total_vectors', models.IntegerField(default=0, help_text='Total number of vectors in collection')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this collection is actively used for new embeddings')),
                ('is_searchable', models.BooleanField(default=True, help_text='Whether this collection is included in searches')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenant_vector_collections',
            },
        ),
        migrations.AlterModelOptions(
            name='embeddingjob',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='modelversion',
            options={'ordering': ['-activated_at', '-created_at']},
        ),
        migrations.RenameField(
            model_name='embeddingjob',
            old_name='failed_detections',
            new_name='failed_items',
        ),
        migrations.RenameField(
            model_name='embeddingjob',
            old_name='processed_detections',
            new_name='processed_items',
        ),
        migrations.RemoveField(
            model_name='embeddingjob',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='embeddingjob',
            name='total_detections',
        ),
        migrations.RemoveField(
            model_name='embeddingjob',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='embeddingjob',
            name='job_type',
            field=models.CharField(choices=[('images', 'Images'), ('detections', 'Detections'), ('migration', 'Model Migration')], default='detections', max_length=50),
        ),
        migrations.AddField(
            model_name='embeddingjob',
            name='total_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='activated_at',
            field=models.DateTimeField(blank=True, help_text='When this model was activated', null=True),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='avg_inference_time_ms',
            field=models.FloatField(blank=True, help_text='Average inference time in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Model-specific configuration parameters'),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='When this model was deactivated', null=True),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the model version'),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='model_type',
            field=models.CharField(choices=[('clip', 'CLIP (OpenAI)'), ('dinov2', 'DINOv2 (Meta)'), ('perception', 'Perception Encoder'), ('sam3', 'SAM3')], default='clip', help_text='Type of embedding model', max_length=50),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='embeddingjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='embeddingjob',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_jobs', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='modelversion',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, help_text='Currently active model (only one can be active)'),
        ),
        migrations.AlterField(
            model_name='modelversion',
            name='name',
            field=models.CharField(help_text='Model identifier (e.g., clip-vit-b-32, dinov2-base)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='modelversion',
            name='vector_dimension',
            field=models.IntegerField(help_text='Dimension of embedding vectors'),
        ),
        migrations.AlterField(
            model_name='modelversion',
            name='version',
            field=models.CharField(help_text='Model version string', max_length=50),
        ),
        migrations.AddIndex(
            model_name='embeddingjob',
            index=models.Index(fields=['model_version', 'status'], name='embedding_j_model_v_eaddf8_idx'),
        ),
        migrations.AddIndex(
            model_name='modelversion',
            index=models.Index(fields=['model_type', 'is_active'], name='model_versi_model_t_4d2d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='modelversion',
            index=models.Index(fields=['is_active', 'activated_at'], name='model_versi_is_acti_752dab_idx'),
        ),
        migrations.AddField(
            model_name='tenantvectorcollection',
            name='model_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_collections', to='embeddings.modelversion'),
        ),
        migrations.AddField(
            model_name='tenantvectorcollection',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vector_collections', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='embeddingjob',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='embeddings.tenantvectorcollection'),
        ),
        migrations.AddIndex(
            model_name='tenantvectorcollection',
            index=models.Index(fields=['tenant', 'is_active'], name='tenant_vect_tenant__f65e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantvectorcollection',
            index=models.Index(fields=['tenant', 'is_searchable'], name='tenant_vect_tenant__823507_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantvectorcollection',
            index=models.Index(fields=['collection_name'], name='tenant_vect_collect_ad723e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantvectorcollection',
            unique_together={('tenant', 'model_version')},
        ),
    ]
