# Generated by Django 4.2 on 2026-03-24 17:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_domain_tenant_location_tenant_timezone'),
        ('media', '0009_detection_detection_count_video_detection_count_and_more'),
        ('embeddings', '0002_tenantvectorcollection_alter_embeddingjob_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantHazardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Profile name (e.g. "Default Inspection Profile")', max_length=100)),
                ('prompts', models.JSONField(help_text='List of text prompts for detection, e.g. ["metallic pipe", "rust", "container"]')),
                ('detection_backend', models.CharField(choices=[('sam3_perceptra', 'SAM3 (perceptra-seg)')], default='sam3_perceptra', help_text='Detection backend to use', max_length=50)),
                ('confidence_threshold', models.FloatField(default=0.3, help_text='Minimum confidence score to keep a detection (0-1)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active configs are evaluated on every new image upload')),
                ('is_default', models.BooleanField(default=False, help_text='Default config used when no specific config ID is provided')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Backend-specific extra configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazard_configs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_hazard_configs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_job_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('detection_backend', models.CharField(choices=[('sam3_perceptra', 'SAM3 (perceptra-seg)')], default='sam3_perceptra', max_length=50)),
                ('total_detections', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('inference_time_ms', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hazard_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_jobs', to='embeddings.tenanthazardconfig')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_jobs', to='media.image')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_jobs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'detection_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tenanthazardconfig',
            index=models.Index(fields=['tenant', 'is_active'], name='tenant_haza_tenant__93f1f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenanthazardconfig',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='detectionjob',
            index=models.Index(fields=['tenant', 'status'], name='detection_j_tenant__e76e0f_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionjob',
            index=models.Index(fields=['image', 'status'], name='detection_j_image_i_16d7b4_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionjob',
            index=models.Index(fields=['created_at'], name='detection_j_created_49722d_idx'),
        ),
    ]
