# Generated by Django 4.2 on 2026-03-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_tenant_domain_tenant_location_tenant_timezone"),
        ("embeddings", "0003_tenanthazardconfig_detectionjob_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tenantvectorcollection",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="tenantvectorcollection",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("embeddings", "Primary embeddings"),
                    ("deltas", "Temporal delta vectors"),
                    ("fusion", "Multi-model fusion vectors"),
                ],
                default="embeddings",
                help_text="What kind of vectors this collection stores",
                max_length=30,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tenantvectorcollection",
            unique_together={("tenant", "model_version", "purpose")},
        ),
        migrations.AddIndex(
            model_name="tenantvectorcollection",
            index=models.Index(
                fields=["tenant", "purpose"], name="tenant_vect_tenant__540f77_idx"
            ),
        ),
    ]
