# Generated by Django 4.2 on 2026-03-05 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_tenant_domain_tenant_location_tenant_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(help_text='Friendly name for the API key', max_length=100)),
                ('key_prefix', models.CharField(db_index=True, help_text='First 8 characters of the key (for identification)', max_length=8, unique=True)),
                ('key_hash', models.CharField(help_text='SHA-256 hash of the full key', max_length=128, unique=True)),
                ('permissions', models.CharField(choices=[('read', 'Read Only'), ('write', 'Read & Write'), ('admin', 'Admin (Full Access)')], default='read', help_text='Permission level for this API key', max_length=20)),
                ('scopes', models.JSONField(blank=True, default=list, help_text='List of allowed scopes/endpoints')),
                ('rate_limit_per_minute', models.IntegerField(default=60, help_text='Maximum requests per minute')),
                ('rate_limit_per_hour', models.IntegerField(default=1000, help_text='Maximum requests per hour')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this key was used', null=True)),
                ('total_requests', models.BigIntegerField(default=0, help_text='Total number of requests made with this key')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this key is active')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this key expires (null = never)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_ips', models.JSONField(blank=True, default=list, help_text='List of allowed IP addresses (empty = allow all)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='tenants.tenant')),
            ],
            options={
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKeyUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('request_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('response_time_ms', models.IntegerField(help_text='Response time in milliseconds')),
                ('error_message', models.TextField(blank=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='api_keys.apikey')),
            ],
            options={
                'db_table': 'api_key_usage_logs',
                'ordering': ['-request_time'],
            },
        ),
        migrations.AddIndex(
            model_name='apikeyusagelog',
            index=models.Index(fields=['api_key', 'request_time'], name='api_key_usa_api_key_a49dc5_idx'),
        ),
        migrations.AddIndex(
            model_name='apikeyusagelog',
            index=models.Index(fields=['request_time'], name='api_key_usa_request_2c18b5_idx'),
        ),
        migrations.AddIndex(
            model_name='apikeyusagelog',
            index=models.Index(fields=['ip_address'], name='api_key_usa_ip_addr_a3205e_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['tenant', 'is_active'], name='api_keys_tenant__aa40c3_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key_prefix'], name='api_keys_key_pre_9c2634_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['expires_at'], name='api_keys_expires_f68b1a_idx'),
        ),
    ]
