# Generated by Django 4.2 on 2026-03-16 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_keys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='owned_by',
            field=models.ForeignKey(blank=True, help_text='User this key acts on behalf of. Null = key owner is the creator.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_api_keys', to=settings.AUTH_USER_MODEL),
        ),
    ]
