# Generated by Django 4.2 on 2026-02-20 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0003_tenant_domain_tenant_location_tenant_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('file_path', models.CharField(max_length=512)),
                ('filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField()),
                ('duration_seconds', models.FloatField(null=True)),
                ('plant_site', models.CharField(db_index=True, max_length=100)),
                ('shift', models.CharField(blank=True, max_length=50, null=True)),
                ('inspection_line', models.CharField(blank=True, max_length=100, null=True)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'videos',
                'ordering': ['-recorded_at'],
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('file_path', models.CharField(max_length=512)),
                ('filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('frame_number', models.IntegerField(blank=True, null=True)),
                ('timestamp_in_video', models.FloatField(blank=True, null=True)),
                ('plant_site', models.CharField(db_index=True, max_length=100)),
                ('shift', models.CharField(blank=True, max_length=50, null=True)),
                ('inspection_line', models.CharField(blank=True, max_length=100, null=True)),
                ('captured_at', models.DateTimeField(db_index=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='media.video')),
            ],
            options={
                'db_table': 'images',
                'ordering': ['-captured_at'],
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detection_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('bbox_x', models.FloatField()),
                ('bbox_y', models.FloatField()),
                ('bbox_width', models.FloatField()),
                ('bbox_height', models.FloatField()),
                ('bbox_format', models.CharField(default='normalized', max_length=20)),
                ('label', models.CharField(db_index=True, max_length=100)),
                ('confidence', models.FloatField()),
                ('crop_path', models.CharField(blank=True, max_length=512, null=True)),
                ('vector_point_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('embedding_generated', models.BooleanField(db_index=True, default=False)),
                ('embedding_model_version', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='media.image')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'detections',
                'ordering': ['-created_at'],
                'default_manager_name': 'objects',
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['tenant', 'recorded_at'], name='videos_tenant__ba5e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['tenant', 'plant_site'], name='videos_tenant__fe21eb_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['tenant', 'status'], name='videos_tenant__a08012_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['created_at'], name='videos_created_f84293_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['tenant', 'captured_at'], name='images_tenant__369bda_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['tenant', 'plant_site'], name='images_tenant__10aa72_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['video', 'frame_number'], name='images_video_i_472283_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['created_at'], name='images_created_6cfb32_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['tenant', 'label'], name='detections_tenant__3c54da_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['tenant', 'embedding_generated'], name='detections_tenant__d87861_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['image', 'confidence'], name='detections_image_i_61b63a_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['vector_point_id'], name='detections_vector__af1af6_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['created_at'], name='detections_created_dab329_idx'),
        ),
    ]
