# Generated by Django 4.2 on 2026-02-23 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_domain_tenant_location_tenant_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagged_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Detection Tags',
                'db_table': 'detection_tag',
            },
        ),
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagged_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Image Tags',
                'db_table': 'image_tag',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Tag description')),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color for UI display', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='VideoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagged_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Video Tags',
                'db_table': 'video_tag',
            },
        ),
        migrations.RemoveField(
            model_name='detection',
            name='crop_path',
        ),
        migrations.AddField(
            model_name='detection',
            name='checksum',
            field=models.CharField(blank=True, help_text='SHA-256 checksum of file', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='storage_backend',
            field=models.CharField(choices=[('azure', 'Azure Blob Storage'), ('s3', 'Amazon S3'), ('minio', 'MinIO / S3-compatible'), ('local', 'Local Filesystem')], default='local', help_text='Storage backend type', max_length=20),
        ),
        migrations.AddField(
            model_name='detection',
            name='storage_key',
            field=models.CharField(blank=True, help_text='Full path/key in storage (e.g., org-123/images/2025/img.jpg)', max_length=500),
        ),
        migrations.AddField(
            model_name='image',
            name='checksum',
            field=models.CharField(blank=True, help_text='SHA-256 checksum of file', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='storage_backend',
            field=models.CharField(choices=[('azure', 'Azure Blob Storage'), ('s3', 'Amazon S3'), ('minio', 'MinIO / S3-compatible'), ('local', 'Local Filesystem')], default='local', help_text='Storage backend type', max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='storage_key',
            field=models.CharField(blank=True, help_text='Full path/key in storage (e.g., org-123/images/2025/img.jpg)', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='storage_backend',
            field=models.CharField(choices=[('azure', 'Azure Blob Storage'), ('s3', 'Amazon S3'), ('minio', 'MinIO / S3-compatible'), ('local', 'Local Filesystem')], default='local', help_text='Storage backend type', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='storage_key',
            field=models.CharField(blank=True, help_text='Full path/key in storage (e.g., org-123/images/2025/img.jpg)', max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('tenant', 'storage_key')},
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('tenant', 'storage_key')},
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['storage_backend', 'storage_key'], name='images_storage_b0c7b9_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['storage_backend', 'storage_key'], name='videos_storage_e97d58_idx'),
        ),
        migrations.AddField(
            model_name='videotag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_videos', to='media.tag'),
        ),
        migrations.AddField(
            model_name='videotag',
            name='tagged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videotag',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_tags', to='media.video'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this tag', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='imagetag',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_tags', to='media.image'),
        ),
        migrations.AddField(
            model_name='imagetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_images', to='media.tag'),
        ),
        migrations.AddField(
            model_name='imagetag',
            name='tagged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detectiontag',
            name='detection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_tags', to='media.detection'),
        ),
        migrations.AddField(
            model_name='detectiontag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_detections', to='media.tag'),
        ),
        migrations.AddField(
            model_name='detectiontag',
            name='tagged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='image',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='video',
            name='file_path',
        ),
        migrations.AddField(
            model_name='detection',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='detections', through='media.DetectionTag', to='media.tag'),
        ),
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='images', through='media.ImageTag', to='media.tag'),
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='videos', through='media.VideoTag', to='media.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='videotag',
            unique_together={('video', 'tag')},
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['tenant', 'name'], name='tag_tenant__f5a1a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='imagetag',
            unique_together={('image', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='detectiontag',
            unique_together={('detection', 'tag')},
        ),
    ]
