# Generated by Django 4.2 on 2026-03-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_detectiontag_imagetag_tag_videotag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file_format',
            field=models.CharField(default='jpg', help_text='Image format (jpg, png, tiff, etc.)', max_length=10),
            preserve_default=False,
        ),
    ]
