# Generated by Django 4.2 on 2026-03-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_image_file_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='checksum',
            field=models.CharField(blank=True, help_text='SHA-256 checksum of file', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='file_format',
            field=models.CharField(default='mp4', help_text='Image format (mp4, avi, mov, webm, etc.)', max_length=10),
            preserve_default=False,
        ),
    ]
