# Generated by Django 4.2 on 2026-03-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_video_checksum_video_file_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, help_text='Tag description', null=True),
        ),
    ]
