# Generated by Django 4.2 on 2026-03-08 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0003_tenant_domain_tenant_location_tenant_timezone'),
        ('media', '0005_alter_tag_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('media_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('detection', 'Detection Crop'), ('audio', 'Audio'), ('document', 'Document')], db_index=True, help_text='Type of media', max_length=20)),
                ('storage_backend', models.CharField(choices=[('azure', 'Azure Blob Storage'), ('s3', 'Amazon S3'), ('minio', 'MinIO / S3-compatible'), ('local', 'Local Filesystem')], help_text='Storage backend type', max_length=20)),
                ('storage_key', models.CharField(help_text='Full path/key in storage', max_length=500)),
                ('filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField()),
                ('content_type', models.CharField(default='application/octet-stream', help_text='MIME type', max_length=100)),
                ('checksum', models.CharField(blank=True, help_text='SHA-256 checksum', max_length=64, null=True)),
                ('file_format', models.CharField(help_text='File format (mp4, avi, mov, webm, etc.)', max_length=10)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=20)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['tenant', 'media_type', 'status'], name='media_tenant__dc09a4_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['storage_backend', 'storage_key'], name='media_storage_a95ace_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['tenant', 'created_at'], name='media_tenant__75c44a_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['media_type', 'is_deleted'], name='media_media_t_f84e8a_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['checksum'], name='media_checksu_06737c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='media',
            unique_together={('tenant', 'storage_key')},
        ),
    ]
