# Generated by Django 4.2 on 2026-03-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_media_media_media_tenant__dc09a4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='embedding_generated',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether a vector embedding has been generated for this image'),
        ),
        migrations.AddField(
            model_name='image',
            name='embedding_model_version',
            field=models.CharField(blank=True, help_text='Name of the model version used to generate the embedding', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='vector_point_id',
            field=models.CharField(blank=True, help_text='ID of the corresponding point in the vector store', max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['tenant', 'embedding_generated'], name='images_tenant__7c9051_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['vector_point_id'], name='images_vector__24e53d_idx'),
        ),
    ]
