# Generated by Django 4.2 on 2026-03-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_detection_created_by_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='detection_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of detections on this image'),
        ),
        migrations.AddField(
            model_name='video',
            name='detection_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of detections across all frames of this video'),
        ),
        migrations.AddField(
            model_name='video',
            name='frame_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of frames extracted from this video'),
        ),
    ]
