# Generated by Django 4.2 on 2026-03-24 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0003_tenanthazardconfig_detectionjob_and_more'),
        ('media', '0009_detection_detection_count_video_detection_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='detection_job',
            field=models.ForeignKey(blank=True, help_text='The auto-detection job that created this detection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='embeddings.detectionjob'),
        ),
        migrations.AddField(
            model_name='detection',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Upload'), ('auto', 'Automatic Detection')], db_index=True, default='manual', help_text='How this detection was created', max_length=20),
        ),
    ]
