# Generated by Django 4.2 on 2026-03-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0010_detection_detection_job_detection_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detection",
            name="detection_count",
        ),
        migrations.AddField(
            model_name="image",
            name="detection_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of detections on this image"
            ),
        ),
    ]
