# Generated by Django 4.2 on 2026-03-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0011_remove_detection_detection_count_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="detection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("checksum__isnull", False)),
                fields=("image", "checksum"),
                name="unique_detection_per_image_checksum",
            ),
        ),
    ]
